# Basics

In [ ]:
import torch
import numpy as np

from tqdm.auto import tqdm

import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm

import mdtraj as md
import nglview as nv

PHI_ANGLE = [4, 6, 8, 14]
PSI_ANGLE = [6, 8, 14, 16]
ALANINE_HEAVY_ATOM_IDX = [1, 4, 5, 6, 8, 10, 14, 15, 16, 18]

In [2]:
def compute_dihedral(positions):
	"""http://stackoverflow.com/q/20305272/1128289"""
	def dihedral(p):
		if not isinstance(p, np.ndarray):
			p = p.numpy()
		b = p[:-1] - p[1:]
		b[0] *= -1
		v = np.array([v - (v.dot(b[1]) / b[1].dot(b[1])) * b[1] for v in [b[0], b[2]]])
		
		# Normalize vectors
		v /= np.sqrt(np.einsum('...i,...i', v, v)).reshape(-1, 1)
		b1 = b[1] / np.linalg.norm(b[1])
		x = np.dot(v[0], v[1])
		m = np.cross(v[0], b1)
		y = np.dot(m, v[1])
		
		return np.arctan2(y, x)

	angles = np.array(list(map(dihedral, positions)))
	return angles

# TBG state file

In [4]:
c5 = torch.load("../data/alanine/c5.pt")
print(c5['xyz'])
c5_tbg = c5
c5_tbg['xyz'][:, [0, 1]] = c5_tbg['xyz'][:, [1, 0]] 
print(c5_tbg['xyz'])

tensor([[[1.9185, 0.3272, 2.0062],
         [1.8852, 0.3056, 2.1077],
         [1.9711, 0.2965, 2.1742],
         [1.8267, 0.2137, 2.1094],
         [1.7969, 0.4173, 2.1580],
         [1.6799, 0.3940, 2.1826],
         [1.8542, 0.5357, 2.1737],
         [1.9537, 0.5432, 2.1581],
         [1.7848, 0.6546, 2.2226],
         [1.6778, 0.6439, 2.2048],
         [1.8056, 0.6616, 2.3749],
         [1.7618, 0.7523, 2.4166],
         [1.9126, 0.6649, 2.3954],
         [1.7636, 0.5733, 2.4230],
         [1.8330, 0.7819, 2.1506],
         [1.9476, 0.7890, 2.1079],
         [1.7462, 0.8834, 2.1430],
         [1.6555, 0.8713, 2.1856],
         [1.7780, 1.0114, 2.0802],
         [1.6900, 1.0757, 2.0804],
         [1.8606, 1.0599, 2.1323],
         [1.8047, 0.9939, 1.9760]]])
tensor([[[1.8852, 0.3056, 2.1077],
         [1.9185, 0.3272, 2.0062],
         [1.9711, 0.2965, 2.1742],
         [1.8267, 0.2137, 2.1094],
         [1.7969, 0.4173, 2.1580],
         [1.6799, 0.3940, 2.1826],
         [1.8542, 

In [8]:
torch.save(c5_tbg, "../data/alanine/c5_tbg.pt")

In [3]:
c5_tbg = torch.load("../data/alanine/c5_tbg.pt")
traj = md.Trajectory(c5_tbg['xyz'].numpy(), md.load("../data/alanine/c5-tbg.pdb").topology)
nv = nv.show_mdtraj(traj)
nv

NGLWidget()

In [5]:
c7ax = torch.load("../data/alanine/c7ax.pt")
print(c7ax['xyz'])
c7ax_tbg = c7ax
c7ax_tbg['xyz'][:, [0, 1]] = c7ax_tbg['xyz'][:, [1, 0]] 
print(c7ax_tbg)

tensor([[[ 1.6384,  1.4081, -0.5858],
         [ 1.6530,  1.4752, -0.5012],
         [ 1.7262,  1.5508, -0.5297],
         [ 1.6909,  1.4174, -0.4169],
         [ 1.5200,  1.5391, -0.4663],
         [ 1.4169,  1.4948, -0.5147],
         [ 1.5223,  1.6439, -0.3824],
         [ 1.6138,  1.6741, -0.3522],
         [ 1.4061,  1.7185, -0.3253],
         [ 1.4475,  1.7918, -0.2560],
         [ 1.3353,  1.7961, -0.4365],
         [ 1.2564,  1.8580, -0.3938],
         [ 1.4090,  1.8590, -0.4865],
         [ 1.2926,  1.7296, -0.5116],
         [ 1.3036,  1.6370, -0.2426],
         [ 1.2568,  1.6879, -0.1404],
         [ 1.2674,  1.5159, -0.2814],
         [ 1.3075,  1.4848, -0.3687],
         [ 1.1703,  1.4298, -0.2109],
         [ 1.0690,  1.4587, -0.2391],
         [ 1.1856,  1.3257, -0.2395],
         [ 1.1817,  1.4384, -0.1029]]])
{'xyz': tensor([[[ 1.6530,  1.4752, -0.5012],
         [ 1.6384,  1.4081, -0.5858],
         [ 1.7262,  1.5508, -0.5297],
         [ 1.6909,  1.4174, -0.4169],
  

In [6]:
torch.save(c7ax_tbg, "../data/alanine/c7ax_tbg.pt")